### ISSUE TITLE
Get at the BuildNumber?

### ISSUE THREAD

**Issue by solidcloudio** [4tecture/BuildVersioning#1]
Can I assign the BuildNumber to a variable?

**Comment by marc-mueller** [comment]
We currently add two variables to the build process:
- BuildVersion.Version --> contains the Assembly File Version
- BuildVersion.VersionInfo --> contains the Assembly Info Version

**Comment by marc-mueller** [comment]
We made some updates recently, the following variables are created by the task:
- BuildVersion.Version
- BuildVersion.VersionInfo
- BuildVersion.SemVer
- BuildVersion.AssemblySemVer

Its also documented in the marketplace now: (https://marketplace.visualstudio.com/items?itemName=4tecture.BuildVersioning)[https://marketplace.visualstudio.com/items?itemName=4tecture.BuildVersioning]
