### ISSUE TITLE
Version Regex

### ISSUE THREAD

**Issue by Steve0212a** [4tecture/BuildVersioning#12]
I have a build that has a build number set to yyyyMMdd.Rev.  For example, the fifth build today would be "20180911.5".  I want to set the version in my .Net Core CsProj files to be "2018.09.11.5".  I have version source set to "Build Number" and believe I need to set the Version Extract Pattern to a custom regex.  Is that correct?  What would the regex be in this case to provide the version in the format your plugin needs?  I tried leaving the version extract pattern as "X.X.X.X" and it failed with this error message:

2018-09-11T19:36:48.0346466Z ##[warning]VersionHandler: Could not extract a version from [20180911.7] using pattern [\d+\.\d+\.\d+\.\d+]

One last question - do the version nodes need to exist in the CSProj or will your plugin add them if they are not there?  My CsProj files do not currently have the nodes defined because they are version 1.0.0.0.

Thanks.

**Comment by marc-mueller** [comment]
Thanks for your feedback. Currently it is not possible to achieve what you would like to do. The regex and also the custom one should extract a version number which consists of three or four parts separated with a dot. So adding additional dots is not possible. But actually you could do so when defining the build number.

The csproj files need to have the version tags already included. We do not add them if they are missing. The tasks only replaces. Normally we set them containing a static developer version to be used locally and the build task replaces them accordingly.
