### ISSUE TITLE
Open source code

### ISSUE THREAD

**Issue by simondel** [4tecture/BuildVersioning#13]
I think it would be a great idea to open source the code for this project so others can contribute to it.

**Comment by us292231** [comment]
I strongly agree.  Having issues, not seeing any code changes.  Indications that this is a stale project, or it works for me and that is good enough...

**Comment by marc-mueller** [comment]
Thanks for your feedback. We started to have this extension primarily in use with our customers but now more an more people are using it. We actually wanted to open source it after a major re-design, but as you obviously have noticed, we were really busy with other things and haven't had the time to do so.

We are taking that in consideration and can hopefully follow up soon. Thanks for your understanding and patience.
