### ISSUE TITLE
2 more variables needed

### ISSUE THREAD

**Issue by mregni** [4tecture/BuildVersioning#16]
Hi,

Is there a way to also add "PreReleaseLabel" and "CommitsSinceVersionSource" to the output variables of this task? Should really come in handy for me. They are already in the GitVersion output normally.

Thanks!

**Comment by marc-mueller** [comment]
Hi @mregni 

We extended the variable creation in case GitVersion is selected as version provider. No we set the following additional variables:
- BuildVersion.PreReleaseTag
- BuildVersion.PreReleaseTagWithDash
- BuildVersion.PreReleaseLabel
- BuildVersion.PreReleaseNumber
- BuildVersion.WeightedPreReleaseNumber
- BuildVersion.BuildMetaData
- BuildVersion.BuildMetaDataPadded
- BuildVersion.FullBuildMetaData
- BuildVersion.Sha
- BuildVersion.ShortSha
- BuildVersion.VersionSourceSha
- BuildVersion.CommitsSinceVersionSource
- BuildVersion.CommitsSinceVersionSourcePadded
- BuildVersion.CommitDate

Hope this helps
Marc
