### ISSUE TITLE
Idea: Install GitVersion using NuGet

### ISSUE THREAD

**Issue by EssentialNRG** [4tecture/BuildVersioning#2]
Instead of downloading the latest GitVersion using HTTP (which doesn't support redirects) you could also install it using the nuget package GitVersion.CommandLine.

**Comment by marc-mueller** [comment]
Thanks for sharing your idea with us. We wanted to use the tooling support provided by Micrsoft SDKs. It looks like the bug with the redirect is still not fixed. Nuget is definitely an option, but currently not planned as a short term fix.

If there won't be a fix in the near future, I consider this idea as a valid option.

There are currently two options:
- Install GitVersion on the Build Server and have the exe in the Path variable. Then no installation is needed.
- Store the Zip file on a custom http endpoint without redirects.

**Comment by marc-mueller** [comment]
With the new version of GitVersion we are now using Chocolatey packages (NuGet) as the default installer package format. You can host the chocolatey package under a custom URL, too.
