### ISSUE TITLE
.Net Core - <Version> with Prerelease tag

### ISSUE THREAD

**Issue by jaganmanoharan** [4tecture/BuildVersioning#23]
Hi,
 We are having issues while using this task for our build pipeline.  For .net core projects, pattern matching does not applies to the <Version> element when existing value has the pre-release value. e.g. 2.0.0.1-alpha. Seems like your task's pattern matching only with the 4 units with dots. Am I missing something here or do we have limitation in the tasks? If it is later could you please fix it for us or provide us the alternate.

Detected File Encoding for file ".......\Converter\Converter.csproj": utf8
##[warning]No matches for regex [(<(?:Package)?Version>)(\d+\.\d+\.\d+(?:\.\d+)?)(</(?:Package)?Version>)] found in file .......\Converter\Converter.csproj

We are updating this field using your task by enable the "Append suffix to Assembly Info Version" with the fixed value.
Background.
Our project is .Net Standard which creates NuGet package.
In the .csproj file we do have the below settings
![image](https://user-images.githubusercontent.com/7931741/127766526-75994424-96e2-479e-9947-15c50c1b9d27.png)

As part of the build pipeline, we need to update all the 3 elements.

Please find the below screenshots of task settings.
![image](https://user-images.githubusercontent.com/7931741/127682602-625a6ae5-ee15-4a99-824b-a57a11d2fd03.png)

![image](https://user-images.githubusercontent.com/7931741/127682618-5e32ddb8-68ed-43ca-b78f-be1878fb9748.png)

**Comment by marc-mueller** [comment]
Hi @jaganmanoharan 

Thanks for your feedback. Yes, you are right, our regex for the replacer is quite specific. I need to check some implementation details, but we should be able to loosen that up and replace any value in the element.

It is the first time we see this problem since normally you don't commit versions. So in source code, there is normally just a "developer" version like 0.0.0.1 checked in and this one get's replaced during the build but without committing it. 

We'll have a look into it to change the replacer regex definitions to solve your problem. I'll keep you updated.

**Comment by jaganmanoharan** [comment]
HI @marc-mueller 
Thanks for your prompt response. Much appreciated your help on agreed to provide a fix. Do you mind to give us tentative delivery date? It will help us to plan for our projects dependency.

**Comment by marc-mueller** [comment]
We are currently pretty busy and this issue has a low priority. I'll try to have a look at it next week. If we optimize the Regex, we will go through all the existing regex definition and review them all. This is why we need to plan this internally.

**Comment by marc-mueller** [comment]
We published version 0.17.7879. Could you please try it with your pipeline?

**Comment by jaganmanoharan** [comment]
Thank you. We will verify and come back to you.

**Comment by jaganmanoharan** [comment]
Hi @marc-mueller , tried with the published version 0.17.7879. It works as expected. Much appreciated your timely help to fix this.
