### ISSUE TITLE
Skip tool install / update

### ISSUE THREAD

**Issue by NecatiMeral** [4tecture/BuildVersioning#26]
Hi everyone,

hoping you guys are well. :-)

I've just noticed that the knob `doInstallGitVersion` doesn't change anything. The underlying `dotnet tool update` command is being executed anyway.

```
- task: BuildVersioning@0
  name: BuildVersioning
  displayName: 'Versioning: Calculate build version'
  inputs:
    versionSource: 'gitversion'
    doInstallGitVersion: false
```

We wanted not to use nuget.org as a primary feed. Instead, we want to install the tool from our internal upstream feed. Since the task cannot handle the required authentication, I've created a custom install / update script. This also saves us a few seconds of build time since it doesn't attempts to install / update the tool if it's already up-to-date.

A five-star solution would be:
- If `GitVersionInstallerVersion` is specified, first check the installed tools (and versions) before running upgrade command
- Allow to specify a custom `--configfile NuGet.config` argument for the `dotnet tool update` command

Currently, the pipeline looks pretty cluttered with boilerplate:
![image](https://user-images.githubusercontent.com/7882753/174263294-a627fc42-19c5-4f93-b936-683be19c05c5.png)

Attachments:
`dotnet-verify-tool.ps1`: Verifies that a global dotnet tool is installed (and matches the given version).
Usage: `. 'C:\DevOpsAgent\_work\101\templates\tools\dotnet-verify-tool.ps1' -ToolName 'gitversion.tool' -ToolVersion 5.10.3`

```ps1
[CmdletBinding()] param(
    [Parameter(ValueFromPipeLine = $True)] [String]$ToolName,[String]$ToolVersion
)

$ListArgs = @(
    "tool"
    "list"
    "-g"
)
$DotnetListResult = & dotnet $ListArgs 2>&1

$DotnetListResult | Where-Object {
    $_ -match '(.*?)\s+(.*?)\s+(.*?)\s+'
} | ForEach-Object {

    $CurrentToolName = $matches[1]
    $CurrentToolVersion = $matches[2]
    if($CurrentToolName -eq $ToolName)
    {
        if($ToolVersion)
        {
            if($ToolVersion-eq $CurrentToolVersion)
            {
                Write-Host "##vso[task.setvariable variable=$ToolName.installed]true"
                Write-Host "Tool '$ToolName' ($CurrentToolVersion) is installed."
                exit 0
            }
            Write-Host "##vso[task.setvariable variable=$ToolName.installed]false"
            Write-Host "Tool '$ToolName' ($CurrentToolVersion) is installed in another version."
            exit 0
        }
        else
        {
            Write-Host "##vso[task.setvariable variable=$ToolName.installed]true"
            Write-Host "Tool '$ToolName' ($CurrentToolVersion) is installed."
            exit 0
        }
    }
}
Write-Host "##vso[task.setvariable variable=$ToolName.installed]false"
Write-Host "Tool '$ToolName' is not installed."
exit 1
```

**Comment by knoxi** [comment]
@NecatiMeral, Please have a look at the latest version of BuildVersioning.

We have just released a new version of BuildVersioning `0.19.16674` which
* takes into account the setting `doInstallGitVersion` correctly
* has a new setting `GitVersionCustomNugetConfig` for allowing custom nuget config files for the tool installer

**Comment by NecatiMeral** [comment]
Hi,

thanks for the update!
I'll check it out on my next devops iteration.

Definitely will report back!

**Comment by NecatiMeral** [comment]
Works as intended!
