### ISSUE TITLE
iOS: Version is set to MinimumOSVersion instead of CFBundleShortVersionString.

### ISSUE THREAD

**Issue by EssentialNRG** [4tecture/BuildVersioning#3]
It took me a while to find out, but it seems that the MinimumOSVersion is configured instead of the CFBundleShortVersionString variable. 

See below the source info.plist
`<key>CFBundleShortVersionString</key>`
`<string>1.0</string>`
`<key>CFBundleVersion</key>`
`<string>1.0</string>`
`<key>LSRequiresIPhoneOS</key>`
`<true/>`
`<key>MinimumOSVersion</key>`
`<string>9.3</string>`

This file gets transformed into: 
`<key>CFBundleShortVersionString</key>`
`<string>1.0</string>`
`<key>CFBundleVersion</key>`
`<string>2.11.0</string>`
`<key>LSRequiresIPhoneOS</key>`
`<true/>`
`<key>MinimumOSVersion</key>`
`<string>2.11.0</string>`

I also noted that a three digits version number (e.g.: 1.0.0) in a CFBundleVersion is not supported by the regex. Maybe this has something to do with this?

Great extension by the way! Exactly what I've been looking for

**Comment by marc-mueller** [comment]
Hi @EssentialNRG 

Thanks for reporting this issue. We'll analyse the code and come back with a solution.

**Comment by marc-mueller** [comment]
There was actually an error in the regex for the `CFBundleShortVersionString`. I also added an optional third digit to it (replacement search).

But I still don't have any clue why the `MinimumOSVersion` was set with the version number.

There is a new version in the marketplace: 0.1.65 --> could you please test it again and show me the results?

**Comment by EssentialNRG** [comment]
I've checked the new version and it seems to work now. Both the CFBundleShortVersionString and CFBundleVersion are being updated correctly now. Thanks!
